[tool.poetry]
name = "tetris"
version = "0.1.0"
description = ""
authors = ["githubmg <maria.gaska@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
